[package]
name = "rust_arkitect"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_arkitect"
path = "src/lib.rs"

[dependencies]
sample_project = { path = "./sample_project" }
syn = { version = "2.0", features = ["full", "visit"] }
quote = "1.0"
ansi_term = "0.12"