[package]
name = "rust_arkitect"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "2.0", features = ["full", "visit"] }
quote = "1.0"
ansi_term = "0.12"
env_logger = "0.11"
log = "0.4.22"