name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check if tag already exists
        run: |
          if git rev-parse "v$(grep '^version' Cargo.toml | sed 's/version = //g' | tr -d '"' | tr -d ' ')" >/dev/null 2>&1; then
            echo "Tag already exists. Stopping workflow."
            exit 1
          fi

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install cargo-release
        run: cargo install cargo-release

      - name: Run tests
        run: cargo test --verbose

      - name: Configure Cargo registry
        run: cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Release version
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo release --no-confirm --no-publish